name: Build

"on":
  push:
    branches:
      - main
    paths-ignore:
      - "assets/**"
      - "README.md"
  pull_request:
    paths-ignore:
      - "assets/**"
      - "README.md"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
